{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':u'JAL Scheduled Tasks',
          'size':(759, 567),

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileAbout',
                   'label':u'&About',
                   'command':'about',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                   'command':'exit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'Button11', 
    'position':(390, 120), 
    'command':'saveas', 
    'label':'Save as', 
    },

{'type':'StaticText', 
    'name':'usedFileName', 
    'position':(60, 160), 
    'size':(525, -1), 
    'text':'usedFileName', 
    },

{'type':'Button', 
    'name':'Button10', 
    'position':(490, 120), 
    'command':'new', 
    'label':'New', 
    },

{'type':'Button', 
    'name':'Button9', 
    'position':(630, 350), 
    'command':'edittask', 
    'label':'Edit Task', 
    },

{'type':'Button', 
    'name':'Button8', 
    'position':(630, 170), 
    'size':(88, -1), 
    'command':'edinitconfig', 
    'label':'Ed Init Config', 
    },

{'type':'Button', 
    'name':'Button7', 
    'position':(290, 120), 
    'command':'save', 
    'label':'Save', 
    },

{'type':'Button', 
    'name':'Button6', 
    'position':(190, 120), 
    'command':'load', 
    'label':'Load', 
    },

{'type':'Button', 
    'name':'Button4', 
    'position':(630, 270), 
    'command':'deletetask', 
    'label':'Delete Task', 
    },

{'type':'Button', 
    'name':'Button5', 
    'position':(630, 230), 
    'command':'inserttask', 
    'label':'Insert Task', 
    },

{'type':'Choice', 
    'name':'picmodel', 
    'position':(20, 50), 
    'size':(145, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(60, 120), 
    'font':{'faceName': u'Segoe UI', 'family': 'sansSerif', 'size': 12}, 
    'text':'Task List', 
    },

{'type':'Slider', 
    'name':'sliderTmr0', 
    'position':(470, 80), 
    'size':(250, -1), 
    'command':'cmdslider', 
    'labels':False, 
    'layout':'horizontal', 
    'max':256, 
    'min':0, 
    'tickFrequency':10, 
    'ticks':True, 
    'value':50, 
    },

{'type':'StaticText', 
    'name':'info', 
    'position':(20, 90), 
    'size':(427, -1), 
    'text':'StaticText3', 
    },

{'type':'TextField', 
    'name':'inittmr0', 
    'position':(600, 50), 
    'size':(60, -1), 
    'text':'6', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(530, 50), 
    'size':(61, -1), 
    'alignment':'right', 
    'text':'Init TMR0', 
    },

{'type':'Button', 
    'name':'Button3', 
    'position':(630, 120), 
    'command':'generate', 
    'label':'Generate', 
    },

{'type':'Button', 
    'name':'Button2', 
    'position':(630, 450), 
    'command':'movedown', 
    'label':'v', 
    },

{'type':'Button', 
    'name':'Button1', 
    'position':(630, 400), 
    'command':'moveup', 
    'label':'^', 
    },

{'type':'MultiColumnList', 
    'name':'tasklist', 
    'position':(20, 190), 
    'size':(590, 300), 
    'backgroundColor':(255, 255, 255, 255), 
    'columnHeadings':[], 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'Choice', 
    'name':'prescaler', 
    'position':(330, 50), 
    'size':(115, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(120, 10), 
    'font':{'faceName': u'Segoe UI', 'family': 'sansSerif', 'size': 14}, 
    'text':'JAL Scheduled Tasks with TMR0', 
    },

{'type':'Choice', 
    'name':'cpufreq', 
    'position':(170, 50), 
    'size':(155, -1), 
    'items':[], 
    },

] # end components
} # end background
] # end backgrounds
} }
